# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amiclean < Formula
  desc "This tool can be used to cleanup old amis which are unused"
  homepage "https://github.com/steffakasid/trivy-project-scanner"
  version "0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/amiclean/releases/download/0.2/amiclean_0.2_Darwin_x86_64.tar.gz"
      sha256 "eaf68be9c617c51998265b6a1da3cd5d2f713486d2417e8732730e809feae646"

      def install
        bin.install "amiclean"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/amiclean/releases/download/0.2/amiclean_0.2_Darwin_arm64.tar.gz"
      sha256 "d86c83842ba2693525cf4bb328a135539debba25fcb7d9a13da560d59d80f036"

      def install
        bin.install "amiclean"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/amiclean/releases/download/0.2/amiclean_0.2_Linux_arm64.tar.gz"
      sha256 "661779a246f63e001e6515f7aaef0d1d2b26c46034c20df8349c0089934a9c53"

      def install
        bin.install "amiclean"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/amiclean/releases/download/0.2/amiclean_0.2_Linux_x86_64.tar.gz"
      sha256 "812e7d7284354ad0dd591d77ea8e23ae277e46674dd80ce6c3fc534ed23d6ecd"

      def install
        bin.install "amiclean"
      end
    end
  end
end
