# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amiclean < Formula
  desc "This tool can be used to cleanup old amis which are unused"
  homepage "https://github.com/steffakasid/trivy-project-scanner"
  version "0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/amiclean/releases/download/0.2/amiclean_0.2_Darwin_arm64.tar.gz"
      sha256 "f0163d121c7ad0f4812f23a1d3966ca8dd5fb290bd6f677e58a9361932c7f466"

      def install
        bin.install "amiclean"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/amiclean/releases/download/0.2/amiclean_0.2_Darwin_x86_64.tar.gz"
      sha256 "770e84902d3f726b4844d8dc82bba33ab417f8ef58341bee342048a71aa98c2d"

      def install
        bin.install "amiclean"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/amiclean/releases/download/0.2/amiclean_0.2_Linux_arm64.tar.gz"
      sha256 "550c2208450ea1163637c5783dc19619568fa4e5d830afda5ddbe3bb86f01620"

      def install
        bin.install "amiclean"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/amiclean/releases/download/0.2/amiclean_0.2_Linux_x86_64.tar.gz"
      sha256 "3cdb4da058a34dac908eed02db69eacb45adc21721db40cdda8c3c97d4e66f27"

      def install
        bin.install "amiclean"
      end
    end
  end
end
