# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amiclean < Formula
  desc "This tool can be used to cleanup old amis which are unused"
  homepage "https://github.com/steffakasid/trivy-project-scanner"
  version "0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/amiclean/releases/download/0.1/amiclean_0.1_Darwin_arm64.tar.gz"
      sha256 "a70396d3c66701e8b92e84d3433b9bf6348c860b6ee95d547b5bd5d4fbd38ff0"

      def install
        bin.install "amiclean"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/amiclean/releases/download/0.1/amiclean_0.1_Darwin_x86_64.tar.gz"
      sha256 "91f67d549e261b473218837b651255cb8f298efb7c20d91bd823a5d88e575c25"

      def install
        bin.install "amiclean"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/amiclean/releases/download/0.1/amiclean_0.1_Linux_arm64.tar.gz"
      sha256 "f0bae7fb46ab802798e1f740e101ede4492330c94addcc5a638b985df38bf17c"

      def install
        bin.install "amiclean"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/amiclean/releases/download/0.1/amiclean_0.1_Linux_x86_64.tar.gz"
      sha256 "bba56e52fcd0358431feda2cc6442d3b90bb78806706144e81b179eb5cf53524"

      def install
        bin.install "amiclean"
      end
    end
  end
end
